"channel: telegram":
  - changed-files:
      - any-glob-to-any-file:
          - "src/telegram/**"
          - "docs/channels/telegram.md"

"app: web-ui":
  - changed-files:
      - any-glob-to-any-file:
          - "ui/**"
          - "src/gateway/control-ui.ts"
          - "src/gateway/control-ui-shared.ts"
          - "src/gateway/protocol/**"
          - "src/gateway/server-methods/chat.ts"
          - "src/infra/control-ui-assets.ts"

"gateway":
  - changed-files:
      - any-glob-to-any-file:
          - "src/gateway/**"
          - "src/daemon/**"
          - "docs/gateway/**"

"docs":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "docs/concepts/acp-bridge.md"

"cli":
  - changed-files:
      - any-glob-to-any-file:
          - "src/cli/**"

"commands":
  - changed-files:
      - any-glob-to-any-file:
          - "src/commands/**"

"scripts":
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"

"docker":
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "Dockerfile.*"
          - "docker-compose.yml"
          - "docker-compose.coolify.yml"
          - "scripts/docker-setup.sh"
          - ".dockerignore"
          - "scripts/**/*docker*"
          - "scripts/**/Dockerfile*"
          - "scripts/sandbox-*.sh"
          - "src/agents/sandbox*.ts"
          - "src/commands/sandbox*.ts"
          - "src/cli/sandbox-cli.ts"
          - "src/docker-setup.test.ts"
          - "src/config/**/*sandbox*"
          - "docs/cli/sandbox.md"
          - "docs/gateway/sandbox*.md"
          - "docs/install/docker.md"
          - "docs/multi-agent-sandbox-tools.md"

"agents":
  - changed-files:
      - any-glob-to-any-file:
          - "src/agents/**"

"security":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/cli/security.md"
          - "docs/gateway/security.md"
