export const browserCoreExamples = [
  "crocbot browser status",
  "crocbot browser start",
  "crocbot browser stop",
  "crocbot browser tabs",
  "crocbot browser open https://example.com",
  "crocbot browser focus abcd1234",
  "crocbot browser close abcd1234",
  "crocbot browser screenshot",
  "crocbot browser screenshot --full-page",
  "crocbot browser screenshot --ref 12",
  "crocbot browser snapshot",
  "crocbot browser snapshot --format aria --limit 200",
  "crocbot browser snapshot --efficient",
  "crocbot browser snapshot --labels",
];

export const browserActionExamples = [
  "crocbot browser navigate https://example.com",
  "crocbot browser resize 1280 720",
  "crocbot browser click 12 --double",
  'crocbot browser type 23 "hello" --submit',
  "crocbot browser press Enter",
  "crocbot browser hover 44",
  "crocbot browser drag 10 11",
  "crocbot browser select 9 OptionA OptionB",
  "crocbot browser upload /tmp/file.pdf",
  'crocbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "crocbot browser dialog --accept",
  'crocbot browser wait --text "Done"',
  "crocbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "crocbot browser console --level error",
  "crocbot browser pdf",
];
